workflow:
  auto_cancel:
    on_new_commit: interruptible

include:
  #needed by docker-image and other jobs
  - project: Infrastructure/freedesktop-ci-templates
    file: templates/fedora.yml
  #needed by check-commit-log job
  - project: Infrastructure/freedesktop-ci-templates
    file: templates/ci-fairy.yml
    ref: aec7a6ce7bb38902c70641526f6611e27141784a


##################################################
# There are four "TYPES" of pipelines on our CI: #
##################################################

## On MERGE REQUESTS.
.pipeline_merge: &CI_MERGE
  if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  interruptible: true

## On COMMITS except tags.
.pipeline_commit: &CI_COMMIT
  if: '$CI_PIPELINE_SOURCE == "push" && $CI_OPEN_MERGE_REQUESTS == null && $CI_COMMIT_TAG == null'
  interruptible: true

## On RELEASES.
.pipeline_release: &CI_RELEASE
  if: '$CI_COMMIT_TAG != null'
  interruptible: false

## On CUSTOM builds though web GUI, API or schedules.
.default:
  interruptible: false


  # Common jobs behavior
  extends: .fdo.distribution-image@fedora
  rules:
    #Similar logic of gimp gitlab-ci.yml. See: https://gitlab.gnome.org/GNOME/babl/-/work_items/119
    - <<: *CI_MERGE
    - <<: *CI_COMMIT
    - <<: *CI_RELEASE
    - if: '$CI_PIPELINE_SOURCE == "web"'
  needs: ["docker-image"]
  variables:
    ###
    # IMPORTANT
    # These are the version tags for the docker images the CI runs against.
    # If you are hacking on them or need a them to rebuild, its enough
    # to change any part of the string of the image you want.
    ###
    FDO_DISTRIBUTION_TAG: '2026-06-20.0'
    FDO_DISTRIBUTION_VERSION: '42'
    FDO_DISTRIBUTION_PACKAGES: >
      meson ninja-build gcc g++ git gettext glib2-devel libjpeg-turbo-devel
      libpng-devel json-glib-devel lcms2-devel diffutils shellcheck devscripts
      clang-tools-extra
    FDO_UPSTREAM_REPO: $CI_PROJECT_PATH
    # Enable colorful output when supported (e.g. ninja)
    CLICOLOR_FORCE: "1"
    # Disable timestamps on CI logs
    FF_TIMESTAMPS: false
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    when: always

.artifacts_durations:
  deps_duration: &short_expire "4 hours"
  build_duration: &mid_expire "2 days"
  dist_duration: &long_expire "8 days"

stages:
  - dependencies
  - build
  - analysis


docker-image:
  extends:
    - .default
    - .fdo.container-build@fedora
  needs: []
  stage: dependencies
  variables:
    GIT_STRATEGY: none

fedora-x86_64:
  extends: .default
  stage: build
  script:
    - git clone --depth 1 https://gitlab.gnome.org/GNOME/babl.git
    - cd babl && meson _build && ninja -C _build && ninja -C _build install && cd ..
    - meson setup --buildtype debug
                  --fatal-meson-warnings
                  --default-library=both
                  _build
    - ninja -C _build
  artifacts:
    paths:
      - "_build/meson-logs"
    expire_in: *long_expire


## Analysis ##

clang-format:
  extends: .default
  rules:
    - <<: *CI_MERGE
  stage: analysis
  script:
    - curl -sL "https://gitlab.gnome.org/GNOME/gimp/-/raw/master/.gitlab/search-common-ancestor.sh" -o /tmp/search-common-ancestor.sh || true
    - if [ $(diff .gitlab/search-common-ancestor.sh /tmp/search-common-ancestor.sh | wc -l) -ne 0 ]; then printf '\033[31m(ERROR)\033[0m search-common-ancestor.sh differs from upstream GIMP. Please sync.\n'; exit 1; fi
    - curl -sL "https://gitlab.gnome.org/GNOME/gimp/-/raw/master/.gitlab/run_style_check_diff.sh" -o /tmp/run_style_check_diff.sh || true
    - if [ $(diff .gitlab/run_style_check_diff.sh /tmp/run_style_check_diff.sh | wc -l) -ne 0 ]; then printf '\033[31m(ERROR)\033[0m run_style_check_diff.sh differs from upstream GIMP. Please sync.\n'; exit 1; fi
    - curl -sL "https://gitlab.gnome.org/GNOME/gimp/-/raw/master/.clang-format" -o /tmp/.clang-format || true
    - if [ $(diff .clang-format /tmp/.clang-format | wc -l) -ne 0 ]; then printf '\033[31m(ERROR)\033[0m .clang-format differs from upstream GIMP. Please sync.\n'; exit 1; fi
    - sh .gitlab/run_style_check_diff.sh
  allow_failure: true #.clang-format file can be imperfect and produce false positives
  artifacts:
    when: on_failure
    paths:
      - fetch_upstream.log
      - fetch_origin.log
    expire_in: *mid_expire

check-commit-log:
  extends:
    - .default
    - .fdo.ci-fairy
  rules:
    - <<: *CI_MERGE
  stage: analysis
  variables:
    GIT_DEPTH: "100"
    JUNIT_REPORT: commit-message-junit-report.xml
  script:
    - curl -sL "https://gitlab.gnome.org/GNOME/gimp/-/raw/master/.gitlab/commit-rules.yml" -o /tmp/commit-rules.yml || true
    - if [ $(diff .gitlab/commit-rules.yml /tmp/commit-rules.yml | wc -l) -ne 0 ]; then printf '\033[31m(ERROR)\033[0m commit-rules.yml differs from upstream GIMP. Please sync.\n'; exit 1; fi
    - touch "$JUNIT_REPORT"
    - ci-fairy check-commits --textwidth 80 --rules-file=.gitlab/commit-rules.yml --junit-xml=$JUNIT_REPORT
  artifacts:
    reports:
      junit: $JUNIT_REPORT
    expire_in: *mid_expire

meson-health:
  extends: .default
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /^Update.*translation.*/'
      #commits pushed by GNOME Translation Robot do not need this job
      when: never
    - <<: *CI_MERGE
      changes:
        paths:
          - "**/*.build"
          - "**/*.py"
          - "**/*.sh"
          - "**/*.ps1"
          - docs/**/*
          - tools/**/*
          - .gitlab/**/*
          - .gitlab-ci.yml #to test changes on script: below
    - <<: *CI_COMMIT #fallback, runs even without changes
  stage: analysis
  script:
    - curl -sL "https://gitlab.gnome.org/GNOME/gimp/-/raw/master/.gitlab/search-common-ancestor.sh" -o /tmp/search-common-ancestor.sh || true
    - if [ $(diff .gitlab/search-common-ancestor.sh /tmp/search-common-ancestor.sh | wc -l) -ne 0 ]; then printf '\033[31m(ERROR)\033[0m search-common-ancestor.sh differs from upstream GIMP. Please sync.\n'; exit 1; fi
    - curl -sL "https://gitlab.gnome.org/GNOME/gimp/-/raw/master/.gitlab/run_meson_health_diff.sh" -o /tmp/run_meson_health_diff.sh || true
    - if [ $(diff .gitlab/run_meson_health_diff.sh /tmp/run_meson_health_diff.sh | wc -l) -ne 0 ]; then printf '\033[31m(ERROR)\033[0m run_meson_health_diff.sh differs from upstream GIMP. Please sync.\n'; exit 1; fi
    - sh .gitlab/run_meson_health_diff.sh
  allow_failure: true #run_meson_health_diff.sh is not that smart, produce false positives

branches-check:
  extends: .default
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /^Update.*translation.*/'
      #commits pushed by GNOME Translation Robot do not need this job
      when: never
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_OPEN_MERGE_REQUESTS == null && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
      interruptible: true
  stage: analysis
  variables:
    GIT_DEPTH: "0"
  script:
    - curl -sL "https://gitlab.gnome.org/GNOME/gimp/-/raw/master/.gitlab/check_dead_branches.sh" -o /tmp/check_dead_branches.sh || true
    - if [ $(diff -I 'if echo "$branch_name"' .gitlab/check_dead_branches.sh /tmp/check_dead_branches.sh | wc -l) -ne 0 ]; then printf '\033[31m(ERROR)\033[0m check_dead_branches.sh differs from upstream GIMP. Please sync.\n'; exit 1; fi
    - sh .gitlab/check_dead_branches.sh
  allow_failure: true #check_dead_branches.sh checks even the branches not created by the commiter
