GEGL Glossary
-------------

[[connection]]
connection::
    A link/pipe routing image flow between operations within the graph
    goes from an output xref:pad[pad] to an input xref:pad[pad], in
    graph glossary this might also be referred to as an edge.

[[DAG]]
DAG::
    Directed Acyclic Graph, see xref:graph[graph].

[[graph]]
graph::
    A composition of xref:node[nodes], the graph is a xref:DAG[DAG].

[[node]]
node::
    The nodes are connected in the xref:graph[graph]. A node has an
    associated operation or can be constructed graph.

[[operation]]
operation::
    The processing primitive of GEGL, is where the actual image
    processing takes place. Operations are plug-ins and provide the
    actual functionality of GEGL.

[[pad]]
pad::
    The part of a xref:node[node] that exchanges image content. The
    place where image "pipes" are used to connect the various operations
    in the composition.

[[input_pad]]
input pad::
  consumes image data, might also be seen as an image parameter to the
  operation.

[[output_pad]]
output pad::
  a place where data can be requested, multiple input pads can reference
  the same output xref:pad[pad].

[[sampler]]
sampler::
    A resampling strategy used for transformations and warps.

[[property]]
property::
    Properties control the behaviour of operations. Through the use of
    GParamSpecs properties they are self documenting via introspection.
